server:
  port: ${PORT:8081}  # Railway injeta a variável PORT

gg:
  jte:
    development-mode: false
    template-location: src/main/jte

spring:
  datasource:
    url: jdbc:h2:mem:testdb  # Ou jdbc:h2:file:./data/db se quiser persistente
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true  # Opcional: ativa console web do H2

logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR
    org.springframework.orm.jpa: DEBUG
