server:
  port: ${PORT:8081}  # Railway injeta a variável PORT

gg:
  jte:
    development-mode: false  # Desative em produção
    template-location: src/main/jte

spring:
  datasource:
    url: ${DATABASE_URL}  # Injetado automaticamente pelo Railway
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR
    org.springframework.orm.jpa: DEBUG